project:
  type: website

website:
  title: "blogs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/yqwu905
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

